M48
; DRILL file {KiCad 7.0.6} date Tue Aug  6 23:52:01 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-06T23:52:01+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X4.8982Y-2.1606
X6.6698Y-5.8563
T2
X3.8569Y-2.265
X3.8569Y-5.7531
X7.7151Y-2.265
X7.7151Y-3.732
T0
M30
